title: Literate Computing for Reproducible Infrastructure - LC4RI
description: >- # this means to ignore newlines until "baseurl:"
  Literate Computing for Reproducible Infrastructure(LC4RI) is an approach to
  use Jupyter Notebook and Ansible for operations of IT infrastructure. ...
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-115651072-1
plugins:
  - jekyll-feed
