title: Literate Computing for Reproducible Infrastructure - LC4RI
description: Literate Computing for Reproducible Infrastructure(LC4RI) is an approach to use Jupyter Notebook and Ansible for operations of IT infrastructure. ...
baseurl: ""
url: "https://literate-computing.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

repo_url: "https://github.com/Literate-Computing/literate-computing.github.io"

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-115651072-1
plugins:
  - jekyll-feed
